/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminControlRoomRouteImport } from './routes/super-admin.control-room'
import { Route as AppPartnerRouteImport } from './routes/app.partner'
import { Route as AppMerchantRouteImport } from './routes/app.merchant'
import { Route as AppMedicalRouteImport } from './routes/app.medical'
import { Route as AppCustomerRouteImport } from './routes/app.customer'
import { Route as AppCaptainRouteImport } from './routes/app.captain'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminControlRoomRoute = SuperAdminControlRoomRouteImport.update({
  id: '/super-admin/control-room',
  path: '/super-admin/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPartnerRoute = AppPartnerRouteImport.update({
  id: '/app/partner',
  path: '/app/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMerchantRoute = AppMerchantRouteImport.update({
  id: '/app/merchant',
  path: '/app/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/app/medical',
  path: '/app/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomerRoute = AppCustomerRouteImport.update({
  id: '/app/customer',
  path: '/app/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCaptainRoute = AppCaptainRouteImport.update({
  id: '/app/captain',
  path: '/app/captain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/app/captain': typeof AppCaptainRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/partner': typeof AppPartnerRoute
  '/super-admin/control-room': typeof SuperAdminControlRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/app/captain': typeof AppCaptainRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/partner': typeof AppPartnerRoute
  '/super-admin/control-room': typeof SuperAdminControlRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/app/captain': typeof AppCaptainRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/partner': typeof AppPartnerRoute
  '/super-admin/control-room': typeof SuperAdminControlRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/app/captain'
    | '/app/customer'
    | '/app/medical'
    | '/app/merchant'
    | '/app/partner'
    | '/super-admin/control-room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/app/captain'
    | '/app/customer'
    | '/app/medical'
    | '/app/merchant'
    | '/app/partner'
    | '/super-admin/control-room'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/app/captain'
    | '/app/customer'
    | '/app/medical'
    | '/app/merchant'
    | '/app/partner'
    | '/super-admin/control-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  AppCaptainRoute: typeof AppCaptainRoute
  AppCustomerRoute: typeof AppCustomerRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppMerchantRoute: typeof AppMerchantRoute
  AppPartnerRoute: typeof AppPartnerRoute
  SuperAdminControlRoomRoute: typeof SuperAdminControlRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/control-room': {
      id: '/super-admin/control-room'
      path: '/super-admin/control-room'
      fullPath: '/super-admin/control-room'
      preLoaderRoute: typeof SuperAdminControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/partner': {
      id: '/app/partner'
      path: '/app/partner'
      fullPath: '/app/partner'
      preLoaderRoute: typeof AppPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/merchant': {
      id: '/app/merchant'
      path: '/app/merchant'
      fullPath: '/app/merchant'
      preLoaderRoute: typeof AppMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/medical': {
      id: '/app/medical'
      path: '/app/medical'
      fullPath: '/app/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/customer': {
      id: '/app/customer'
      path: '/app/customer'
      fullPath: '/app/customer'
      preLoaderRoute: typeof AppCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/captain': {
      id: '/app/captain'
      path: '/app/captain'
      fullPath: '/app/captain'
      preLoaderRoute: typeof AppCaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  AppCaptainRoute: AppCaptainRoute,
  AppCustomerRoute: AppCustomerRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppMerchantRoute: AppMerchantRoute,
  AppPartnerRoute: AppPartnerRoute,
  SuperAdminControlRoomRoute: SuperAdminControlRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
