// Publisher / author accounts generated by the admin control room.
// Stored locally (platform-level) so the merchant login can authenticate them.
export const PUBLISHER_ACCOUNTS_KEY = "rava_publisher_accounts";

export type PublisherKind = "publisher" | "author";

export type PublisherAccount = {
  id: string;
  user: string;
  pass: string;
  name: string;
  kind: PublisherKind;
  commissionPct: number;
  phone?: string;
  iban?: string;
  features: { digitalLibrary: boolean; campaigns: boolean; splitPayments: boolean };
  active: boolean;
  createdAt: number;
};

export function loadPublisherAccounts(): PublisherAccount[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = JSON.parse(localStorage.getItem(PUBLISHER_ACCOUNTS_KEY) || "[]");
    return Array.isArray(raw) ? (raw as PublisherAccount[]) : [];
  } catch {
    return [];
  }
}

export function savePublisherAccounts(list: PublisherAccount[]) {
  try {
    localStorage.setItem(PUBLISHER_ACCOUNTS_KEY, JSON.stringify(list));
  } catch {
    /* ignore quota errors */
  }
}

// Deterministic-ish username from the display name + short suffix.
export function suggestUsername(name: string, kind: PublisherKind): string {
  const base = (name || kind)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\u0600-\u06FF]+/g, "")
    .slice(0, 10);
  const slug = /[a-z0-9]/.test(base) ? base : kind;
  return `${slug}${Math.floor(100 + Math.random() * 900)}`;
}

export function generatePassword(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
  let out = "";
  for (let i = 0; i < 10; i++) out += chars[Math.floor(Math.random() * chars.length)];
  return out;
}
